# Generated by Django 5.1.2 on 2024-12-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, help_text="Введите номер телефона", null=True, verbose_name="Телефон"),
        ),
    ]
