# Generated by Django 5.1.2 on 2024-11-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите превью блога",
                null=True,
                upload_to="photo/blog/",
                verbose_name="Превью",
            ),
        ),
    ]
