# Generated by Django 5.1.2 on 2024-11-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_description_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение товара",
                null=True,
                upload_to="photo/product/",
                verbose_name="Изображение товара",
            ),
        ),
    ]
