# Generated by Django 5.1.4 on 2024-12-20 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_views_alter_product_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите категорию",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Укажите статус публикации товара", verbose_name="Признак публикации"
            ),
        ),
    ]
